### ISSUE TITLE
How to use multi-tenant on Waflz ?

### ISSUE THREAD

**Issue by lmq1999** [Edgio/waflz#270]
Do you have any examples of how to use multi-tenant on WaflzI? I read the docs but I can't find any useful information about setting waflz for multi-tenant

**Comment by tinselcity** [comment]
It's not so much a setting as it is about the design of the engine to support many custom `profiles` that are built on top of common ruleset(s).  The genesis of our waf engine and why we departed from using [libmodsecurity](https://github.com/SpiderLabs/ModSecurity) at our CDN, was due to how the parsed rulesets (see [OWASP CRS](https://github.com/coreruleset/coreruleset)) are stored in memory.  At our CDN any of our thousands of customer accounts can be served from any physical server anywhere around the world.  Meaning how the rulesets are parsed and used within the server process needs to be handled carefully to keep from blowing up in memory.  So the engine supports things like
- lazy-loading
- read only references to rules/policies

There's some info in the docs about the architecture here:
[https://edgecast.github.io/waflz/overview.html#muti-tenancy-concerns](https://edgecast.github.io/waflz/overview.html#muti-tenancy-concerns)

In terms of the specific implementation, the common parts of the engine are stored centrally in the `engine` object:
[https://github.com/EdgeCast/waflz/blob/master/include/waflz/engine.h](https://github.com/EdgeCast/waflz/blob/master/include/waflz/engine.h)

As to the usage of it.  It's simply a matter of loading different profiles on top of or referring to the same rulesets:
[https://edgecast.github.io/waflz/profiles.html](https://edgecast.github.io/waflz/profiles.html)
